### ISSUE TITLE
Test failure on big endian

### ISSUE THREAD

**Issue by AdrianBunk** [Bodigrim/integer-roots#3]
https://buildd.debian.org/status/fetch.php?pkg=haskell-integer-roots&arch=s390x&ver=1.0.2.0-2&stamp=1696945515&raw=0
https://buildd.debian.org/status/fetch.php?pkg=haskell-integer-roots&arch=ppc64&ver=1.0.2.0-2&stamp=1696946613&raw=0
```
./Math/NumberTheory/Roots/General.hs:174: failure in expression `map isPerfectPower [0..10]'
expected: [True,True,False,False,True,False,False,False,True,True,False]
 but got: [True,True,False,False,True,*** Exception: divide by zero
                                      ^

./Math/NumberTheory/Roots/General.hs:193: failure in expression `map highestPower [0..10]'
expected: [(0,3),(1,3),(2,1),(3,1),(2,2),(5,1),(6,1),(7,1),(2,3),(3,2),(10,1)]
 but got: [(0,3),(1,3),(2,1),(3,1),(2,2),*** Exception: divide by zero
                                         ^

Examples: 23  Tried: 21  Errors: 0  Failures: 2
Test suite integer-roots-doctests: FAIL
```

**Comment by Bodigrim** [comment]
Given that the main test suite passes on big-endian, I think the issue is in GHC bytecode interpreter, not in `integer-roots`. I don't have means to investigate however, maybe you can raise it at GHC issue tracker?

Otherwise you can probably disable doctest test suite, it's the only one going through bytecode interpreter.
